### ISSUE TITLE
Feature Request: Allow editing for healing items

### ISSUE THREAD

**Issue by ViP3R76** [viniHNS/Make-Meds-Great-Again-Server#1]
I would like to see changing options for the healing items, as example:

AFAK 
- allow configuration of stopping light and/or heavybleeding
- allow configuration of curing a fracture
- allow configuration of restoring blacked bodyparts

Why:
For beginners or entry level/just for fun players it removes the hazzle to remember which item needs to be used for which type of injury just making it easier.

**Comment by viniHNS** [comment]
Hi @ViP3R76,

Thank you for your suggestion! I’ve implemented the changes you requested in the latest update, [v1.2.0](https://github.com/viniHNS/Make-Meds-Great-Again-Server/releases/tag/v1.2.0). 
Additionally, I've introduced a new stimulant called Exodrine.

Feel free to download the latest version and let me know if there's anything else you'd like to see improved!

Thank you for your feedback and support 🥇
