### ISSUE TITLE
Exodrine in Handbook (Wrong Category)

### ISSUE THREAD

**Issue by ViP3R76** [viniHNS/Make-Meds-Great-Again-Server#3]
The new Exodrine stimulant shows up in the Handbook in the wrong category. It should be in Stimulants instead of Medicals like Painkillers :-)

**Comment by viniHNS** [comment]
Fixed in the [latest version](https://github.com/viniHNS/Make-Meds-Great-Again-Server/releases/tag/v1.2.3). Exodrine is now correctly listed under *Stimulants*. Thanks for catching that! 😊
